export const heroSkills = {
  1: {
    1: 'mana_break',
    2: 'blink',
    3: 'counterspell',
    4: 'mana_void',
    5: ['counterspell_ally', 'aghanims_shard'],
    6: ['mana_overload', 'aghanims_scepter', 'blink_fragment'],
    7: 'Burns an opponent`s mana on each attack and deals damage equal to a percentage of the mana burnt. Enemies with no mana left are temporarily slowed.',
    8: 'Short distance teleportation that allows Anti-Mage to move in and out of combat.',
    9: [
      'Passively grants magic resistance. Counterspell may be activated to create an anti-magic shell around Anti-Mage that blocks and sends any targeted spells back towards enemies instead.',
      'Counterspell Ally may be activated to create an anti-magic shell around an allied hero that blocks and sends any targeted spells back towards enemies instead. Any time a spell is reflected by Counterspell or Counterspell Ally, an illusion of Anti-Mage will be created next to the enemy.',
    ],
    10: 'For each point of mana missing by the target unit, damage is dealt to it and surrounding enemies.  The main target is also mini-stunned.',
    11: 'Blinks an illusion to the target enemy or location, which attacks for a brief time. Counterspell is replicated on the Blink Fragment illusion. Has 3 Charges.',
  },
  2: {
    1: 'berserkers_call',
    2: 'battle_hunger',
    3: 'counter_helix',
    4: 'culling_blade',
    5: ['counter_helix', 'aghanims_shard'],
    6: ['berserkers_call', 'aghanims_scepter', 'berserkers_call'],
    7: 'Axe taunts nearby enemy units, forcing them to attack him at high speed, while he gains bonus armor during the duration.',
    8: 'Enrages an enemy unit, causing it to take damage over time until it kills another unit or the duration ends. The damage is increased by a factor of Axe`s armor. The enemy is also slowed as long as they are facing away from Axe.',
    9: [
      'After a set number of attacks, Axe will perform a helix counter attack, dealing pure damage to all nearby enemies.',
      'Counter Helix now applies a stacking debuff to enemies hit by it that causes them to deal less total attack damage to Axe. Counter Helix no longer has a cooldown.',
    ],
    10: 'Axe spots a weakness and strikes, dealing pure damage. When an enemy hero is killed with Culling Blade, its cooldown is reset, Axe gains bonus armor permanently and all nearby allied units gain bonus movement speed. ',
    11: 'Berserker`s Call applies Battle Hunger to affected units. Reduces Berserker`s Call cooldown.',
  },
  3: {
    1: 'enfeeble',
    2: 'brain_sap',
    3: 'nightmare',
    4: 'fiends_grip',
    5: ['brain_sap', 'aghanims_shard'],
    6: ['fiends_grip', 'aghanims_scepter', 'fiends_grip'],
    7: 'Deals damage every second and lowers the enemy`s total attack damage and cast range.',
    8: 'Feasts on the vital energies of an enemy unit, healing Bane and dealing damage.',
    9: [
      'Puts the target enemy or friendly Hero to sleep. Sleeping units are awakened when damaged. If the target was directly attacked, the Nightmare passes to the attacking unit. Bane can attack and damage nightmared targets freely with bonus attack speed.',
      'Causes Brain Sap to become a 550 AoE spell. Secondary targets only heal for 30%.',
    ],
    10: 'CHANNELED - Grips an enemy unit, disabling it and causing heavy damage over time, while stealing mana every 0.5 seconds based on the unit`s maximum mana.',
    11: 'Reduces Fiend`s Grip cooldown by 45. Fiend`s Grip now creates two uncontrollable illusions that are also channeling Fiend`s Grip on the target. Illusions take 200% incoming damage and immediately die if they are interrupted. Damage does not stack.',
  },
  4: {
    1: 'bloodrage',
    2: 'blood_bath',
    3: 'thirst',
    4: 'rupture',
    5: ['bloodrage', 'aghanims_shard'],
    6: ['blood_mist', 'aghanims_scepter', 'blood_mist'],
    7: 'Drives Bloodseeker into a bloodthirsty rage which causes him to attack faster and deal more spell damage at the cost of a percentage of his health per second. Provides half attack speed to allied heroes.',
    8: 'Bloodseeker baptizes an area in sacred blood. After 2.9 seconds the ritual completes, causing any enemies caught in the area to take damage and become silenced.',
    9: [
      'Bloodseeker is invigorated by the wounds of his enemies, restoring some life when he kills a unit. Restores for half values when denying, or if an ally kills a nearby enemy hero. Also gains bonus movement speed when an enemy hero`s health falls below 80.0%, with the bonuses increasing as their health falls further. If an enemy hero`s health falls below 25.0%, he will also gain vision and True Sight of that hero. Bonuses stack per hero. Unlocks max movement speed for Bloodseeker.',
      'Bloodrage attacks now deal 1.8% of the target’s max health as pure damage and heals Bloodseeker for that amount. Only works for Bloodseeker.',
    ],
    10: 'Causes an enemy unit`s skin to rupture, dealing initial damage based on its current health. If the unit moves, it takes damage based on the distance moved.',
    11: 'Bloodseeker sprays his blood continuously in the area around him, losing health to damage and slow his enemies. While active, Thirst`s healing is increased. Cannot be turned off while on cooldown. Additionally, passively turns all your overheal from your own abilities into an all damage barrier up to 50% of Bloodseeker`s Max Health. Barrier amount decays by 0.5% per second.',
  },
  5: {
    1: 'crystal_nova',
    2: 'frostbite',
    3: 'brilliance_aura',
    4: 'freezing_field',
    5: ['crystal_clone', 'aghanims_shard'],
    6: ['freezing_field', 'aghanims_scepter', 'freezing_field'],
    7: 'A burst of damaging frost slows enemy movement and attack rate in the targeted area.',
    8: 'Encases an enemy unit in ice, prohibiting movement and attack, while dealing damage over time. Lasts 10.0 seconds on creeps level 6 or lower.',
    9: [
      'Gives additional mana regeneration to all friendly units on the map. Allies within a 1200.0 radius of Crystal Maiden receive 3.0x the mana regeneration. Crystal Maiden herself receives 6.0x the bonus.',
      'Slides backward, creating a crystal clone of herself in her place and disjointing incoming projectiles. If the clone takes enough damage or times out, it shatters, Frostbiting enemies in a 400.0 AoE around its place.',
    ],
    10: 'CHANNELED - Surrounds Crystal Maiden with 100 random icy explosions that slow enemies and deal massive damage. Grants bonus armor while channeling. Lasts 10.0 seconds.',
    11: 'Allows you to move, cast and attack during Freezing Field. Can still be interrupted by enemies. You move 75% slower during this. Increases total number of explosions by 20%. Applies Frostbite to any unit that has been standing in the Freezing Field for over 3.5s.',
  },
  6: {
    1: 'frost_arrows',
    2: 'wave_of_silence',
    3: 'multishot',
    4: 'marksmanship',
    5: ['glacier', 'aghanims_shard'],
    6: ['frost_arrows', 'aghanims_scepter', 'frost_arrows'],
    7: 'Adds a freezing effect to Drow`s attacks, slowing enemy movement and dealing bonus damage.  Slow lasts 1.5 seconds.',
    8: 'Releases a wave that silences and knocks back enemy units. Knockback distance is relative to how close they are to Drow. Drow Gains Movement Speed for the same duration.',
    9: [
      'CHANNELED - Drow releases a flurry of arrows in continuous salvos, hitting enemies for extra damage and applying longer duration Frost Arrows. Lasts up to 1.8 seconds.',
      'Drow Ranger creates a hill of ice beneath her. While standing on the hill, attackers gain bonus attack range and high ground advantage - they cannot miss and gain flying vision. Drow Ranger additionally gets bonus Multishot arrows per wave while on the hill. The front of the hill obscures vision and cannot be moved through except by Drow Ranger.',
    ],
    10: 'Drow`s experiences in battle grant her a chance to launch arrows with incredible accuracy and effectiveness. Pierces through the enemy`s defenses, ignoring their base armor. Grants Drow and nearby ranged heroes with bonus agility based on Drow`s current agility, with allies receiving 50.0% of the bonus Drow receives. This ability is disabled if there is an enemy hero within 400.0 range.',
    11: 'Frost Arrows now apply a Hypothermia stack to enemies, increasing damage from Frost Arrows and reducing their regeneration per stack. If an enemy dies with Hypothermia stacks, they burst and deal damage per stack and slow in an area around it.',
  },
  7: {
    1: 'fissure',
    2: 'enchant_totem',
    3: 'aftershock',
    4: 'echo_slam',
    5: ['fissure', 'aghanims_shard'],
    6: ['enchant_totem', 'aghanims_shard', 'enchant_totem'],
    7: 'Slams the ground with a mighty totem, creating an impassable ridge of stone while stunning and damaging enemy units along its line.',
    8: 'Empowers Earthshaker`s totem, causing it to deal extra damage and have 100.0 bonus attack range on the next attack.',
    9: [
      'Causes the earth to shake underfoot, adding additional damage and stuns to nearby enemy units when Earthshaker casts his abilities.',
      'Reduces Fissure cooldown and allows Earthshaker to walk on it. When he casts any ability, an Aftershock is released along its path that stuns for a shortened duration.',
    ],
    10: 'Shockwaves travel through the ground, damaging enemy units.  Each enemy hit causes an echo to damage nearby units. Real heroes cause two echoes.',
    11: 'Enchant Totem becomes a ground target ability, causing Earthshaker to jump in the air and land at the target spot, casting Enchant Totem there.  Self-casting the ability will behave in the original form, without jumping. Grants Enchant Totem a cleaving attack.',
  },
  8: {
    1: 'blade_fury',
    2: 'healing_ward',
    3: 'blade_dance',
    4: 'omni_slash',
    5: ['blade_fury', 'aghanims_shard'],
    6: ['swift_slash', 'aghanims_scepter', 'swiftslash'],
    7: 'Causes a bladestorm of destructive force around Juggernaut, rendering him debuff immune, increasing his magic resistance by 80%, and dealing damage to nearby enemy units. ',
    8: 'Summons a Healing Ward which heals all nearby allied units, based on their max health.  The Healing Ward moves at 325.0 movement speed after being summoned.  Lasts 25.0 seconds.',
    9: [
      'Gives Juggernaut a chance to deal critical damage on each attack.',
      'Increases movement speed during Blade Fury, and attacks random nearby enemy units with reduced damage.',
    ],
    10: 'Juggernaut leaps towards the target enemy units, and then slashes the target and other nearby enemy units at an increased attack rate. Juggernaut is invulnerable for the duration',
    11: 'Performs a short Omnislash for 1.0 seconds.',
  },
  9: {
    1: 'starfall',
    2: 'arrow',
    3: 'leap',
    4: 'invis',
    5: ['leap', 'aghanims_shard'],
    6: ['arrow', 'aghanims_scepter', 'sacred_arrow'],
    7: 'Calls down a wave of meteors to damage nearby enemy units. The closest enemy unit to Mirana in a 650.0 radius will be struck a second time for 75.0% of the damage.',
    8: 'Fires a long-range arrow with deadly precision, which stuns and damages the first enemy unit it strikes. The stun duration ranges from 0.0 to 2.6 seconds, with bonus damage up to 150.0 added, based on the distance the arrow travels to its target. Instantly kills the first non-ancient creep it hits.',
    9: [
      'Mirana leaps forward into battle, empowering herself with a ferocious roar that grants bonus attack and movement speed. Speed bonus lasts 4.0 seconds.',
      'Upon landing, launches a projectile along Sagan`s leap path, dealing damage and slowing units affected. Leap does not break Moonlight Shadow invisibility.',
    ],
    10: 'Turns Mirana and all allied heroes invisible and grants bonus movement speed. If a hero is revealed, invisibility will restore after the fade delay as long as Moonlight Shadow`s duration has not expired.',
    11: 'Causes Sacred Arrow to release a Starstorm on enemies along the travel path of the primary arrow, releasing a second Starstorm that deals less damage to the impacted unit.',
  },
  10: {
    1: 'waveform',
    2: 'adaptive_strike_agi',
    3: 'adaptive_strike_str',
    4: 'replicate',
    5: ['adaptive_strike_agi', 'aghanims_shard'],
    6: ['replicate', 'aghanims_scepter', 'morph'],
    7: 'Morphling dissolves into liquid and surges forward, damaging enemy units in his path. Morphling is invulnerable during Waveform.',
    8: 'Launches a surge of water toward an enemy unit, dealing base damage plus additional damage based on Morphling`s agility times a multiplier. If Morphling`s agility is 50% higher than strength, the maximum agility multiplier is used. Passively grants bonus Agility.',
    9: [
      'Launches a surge of water toward an enemy unit, stunning and knocking back the target based on Morphling`s strength. If his strength is 50% higher than his agility, the maximum stun/knockback is dealt. Passively grants bonus Strength.',
      'Increases bonus Agility.',
    ],
    10: 'Morphling changes his form to match the targeted enemy, gaining their basic abilities. Can be toggled for the duration of the ability.',
    11: 'Adds an alt-cast to Morph. When enabled, a strong illusion is created of the target hero that can cast all of the hero`s basic abilities. If the illusion is alive when Morphling toggles the ability, he will take the place of the illusion, destroying it.',
  },

  137: {
    1: 'onslaught',
    2: 'trample',
    3: 'uproar',
    4: 'pulverize',
    5: ['rock_throw', 'aghanims_shard'],
    6: ['uproar', 'aghanims_scepter', 'uproar'],
    7: 'Primal Beast charges up and then runs in the chosen direction, knocking back enemies and allies alike. Enemy units are damaged and stunned on impact. The longer the charge duration, the farther Primal Beast`s momentum will carry him. Can be cancelled at any time with the Stop command.',
    8: 'Primal Beast stomps over everything. For every 140.0 units traveled, all enemies around the Beast receive damage. Deals base damage plus a multiplier of Primal Beast`s attack damage. Primal Beast is disarmed for the duration of the ability.',
    9: [
      'The Beast`s temper passively provides bonus damage. Additionally, for every instance of 50.0 damage or more Primal Beast takes from enemy heroes, he accumulates stacks of Uproar. When activated, Primal Beast releases a roar that slows surrounding enemies and grants the Beast additional attack damage and armor for 7.0 seconds based on his current stacks of Uproar.',
      'Primal Beast throws a rock at the target location that stuns and damages enemies. The rock cannot be thrown within a minimum range of Primal Beast. After landing, the rock splits into 3 additional fragments that land behind the initial target location. Rock Throw increases stacks of Uproar for each hero hit.',
    ],
    10: 'CHANNELED - Primal Beast channels his rage, grabbing the target enemy and slamming them into the ground repeatedly, damaging and mini-stunning any enemies caught in the AoE. Each consecutive hit deals bonus damage. Lasts 2.3 seconds.',
    11: 'When Primal Beast activates Uproar, he releases 3.0 waves of 2.0 projectiles per stack of uproar each in a circle around him. Projectiles deal damage and Break enemies hit. After a short delay, each projectile splinters in two.',
  },
  138: {
    1: 'dead_shot',
    2: 'the_calling',
    3: 'gunslinger',
    4: 'pierce_the_veil',
    5: ['pierce_the_veil', 'aghanims_shard'],
    6: ['parting_shot', 'aghanims_scepter', 'parting_shot'],
    7: 'Muerta fires a ghostly trickshot at an enemy unit or tree. When the bullet strikes, it damages and briefly slows, then ricochets in the targeted direction. The ricochet damages all units that it passes through, stopping when it hits a hero. Heroes hit by the ricochet are feared away from the impact.',
    8: ' Summons a group of 4.0 revenants that slowly circle the targeted location. Enemies within the area are slowed and have reduced attack speed. Revenants deal damage and silence enemies as they pass through them. Enemy heroes killed inside the Calling refresh its duration and create another Revenant.',
    9: [
      ' Muerta`s attacks have a chance to fire a second shot at another target, prioritizing Heroes.',
      'Muerta gains 30.0% Spell Lifesteal during Pierce the Veil. While Pierce the Veil is active Muerta permanently gains 2.0% spell amplification each time she kills an enemy Hero or they die in her vicinity.',
    ],
    10: ' Muerta transforms, becoming immune to physical damage. All of her attack damage is dealt as magical damage. Muerta gains bonus attack damage and phased movement. Muerta can attack ethereal units, but deals no damage to Magic Immune targets.',
    11: 'Muerta precisely shoots a hero in their soul, separating it from their physical body and knocking it 150.0 units away.The soul is untargetable, muted, disarmed, and invulnerable for 4.0 seconds.The body is stunned and has 35.0% damage reduction for this duration.After the effect ends the hero`s soul is forcefully returned to their body applying a strong dispel. The soul will survive until the end of the effect even if the hero is killed.',
  },
};

//  10: {
//     1: '',
// 2: '',
// 3: '',
// 4: '',
// 5: '',
// 6: '',
// 7: '',
// 8: '',
// 9: '',
// 10: '',
// 11: '',
//   },
