export const heroSkills = {
  1: {
    1: 'mana_break',
    2: 'blink',
    3: 'counterspell',
    4: 'mana_void',
    5: 'aghanims_shard',
    6: 'aghanism_scepter',
    7: 'Spala manę wroga z każdym atakiem i zadaje celowi obrażenia równe pewnemu procentowi spalonej many. Jednostki bez many są spowalniane na krótki czas',
    8: 'Krótkodystansowa teleportacja która umożliwia Anti-Mage`owi wkraczanie do walki i opuszczanie jej',
    9: 'Pasywne zapewnia odporność na magię. Counterspell może zostać aktywowane, by otoczyć Anti-Mage`a antymagiczną powłoką,która zablokuje i odbije wszelkie czary celowane z powrotem w stronę rzucającego.',
    10: 'Każdy brakujący punkt many wybranej jednostki powoduje obrażenia,które są zadawane jej oraz pobliskim wrogom. Na główny cel zostanie także nałożone miniogłuszenie.',
  },
  2: {
    1: 'berserkers_call',
    2: 'battle_hunger',
    3: 'counter_helix',
    4: 'culling_blade',
    5: 'counter_helix',
    6: 'berserkers_call',
    7: '',
    8: '',
    9: '',
    10: '',
  },
  3: {
    1: 'enfeeble',
    2: 'brain_sap',
    3: 'nightmare',
    4: 'fiends_grip',
    5: 'brain_sap ',
    6: 'fiends_grip',
    7: '',
    8: '',
    9: '',
    10: '',
  },
  4: {
    1: 'bloodrage',
    2: 'blood_bath',
    3: 'thirst',
    4: 'rupture',
    5: 'bloodrage',
    6: 'blood_mist',
    7: '',
    8: '',
    9: '',
    10: '',
  },
  5: {
    1: 'crystal_nova',
    2: 'frostbite',
    3: 'brilliance_aura',
    4: 'freezing_field',
    5: 'crystal_clone',
    6: 'freezing_field',
    7: '',
    8: '',
    9: '',
    10: '',
  },
  6: {
    1: 'frost_arrows',
    2: 'wave_of_silence',
    3: 'multishot',
    4: 'marksmanship',
    5: 'aghs_shard',
    6: 'aghs_scepter',
    7: '',
    8: '',
    9: '',
    10: '',
  },
  7: {
    1: 'fissure',
    2: 'enchant_totem',
    3: 'aftershock',
    4: 'echo_slam',
    5: '',
    6: '',
    7: '',
    8: '',
    9: '',
    10: '',
  },
};
