export const heroSkills = {
  1: {
    1: 'mana_break',
    2: 'blink',
    3: 'counterspell',
    4: 'mana_void',
    5: 'counterspell_ally',
    6: 'mana_overload',
    7: 'Spala manę wroga z każdym atakiem i zadaje celowi obrażenia równe pewnemu procentowi spalonej many. Jednostki bez many są spowalniane na krótki czas',
    8: 'Krótkodystansowa teleportacja która umożliwia Anti-Mage`owi wkraczanie do walki i opuszczanie jej',
    9: 'Pasywne zapewnia odporność na magię. Counterspell może zostać aktywowane, by otoczyć Anti-Mage`a antymagiczną powłoką,która zablokuje i odbije wszelkie czary celowane z powrotem w stronę rzucającego.',
    10: 'Każdy brakujący punkt many wybranej jednostki powoduje obrażenia,które są zadawane jej oraz pobliskim wrogom. Na główny cel zostanie także nałożone miniogłuszenie.',
  },
  2: {
    1: 'berserkers_call',
    2: 'battle_hunger',
    3: 'counter_helix',
    4: 'culling_blade',
    5: 'counter_helix',
    6: 'berserkers_call',
    7: 'Axe szydzi z pobliskich jednostek wroga, zmuszając je do atakowania go z dużą prędkością, podczas gdy on sam zyskuje bonusową zbroję przez czas trwania umiejętności.',
    8: 'Wścieka wroga, powodując, że odnosi obrażenia w czasie, aż zabije inną jednostkę lub do momentu zakończenia trwania umiejętności. Obrażenia są zwiększane o współczynnik pancerza Axe`a. Przeciwnik jest także spowolniony, jeśli zwraca się plecami do Axe`a.',
    9: 'Po określonej liczbie ataków, Axe przeprowadza kontratak wirujący, zadając czyste obrażenia wszystkim pobliskim wrogom.',
    10: 'Axe zauważa słabe punkty wroga i atakuje, zadając obrażenia pełne. Przy zabójstwie wrogiego bohatera przy pomocy Culling Blade czas oczekiwania resetuje się, Axe zyskuje trwała premię do pancerza, a wszystkie pobliskie sojusznicze jednostki zyskują premię do szybkości ruchu. ',
  },
  3: {
    1: 'enfeeble',
    2: 'brain_sap',
    3: 'nightmare',
    4: 'fiends_grip',
    5: 'brain_sap ',
    6: 'fiends_grip',
    7: 'Zadaje obrażenia co sekundę i obniża całkowite obrażenia atakowe przeciwnika oraz zasięg rzutu.',
    8: 'Żeruje na siłach witalnych wrogiej jednostki, zadając jej obrażenia i przywracając zdrowie Bane`owi.',
    9: 'Usypia celowanego wroga lub sojuszniczego bohatera. Usypione jednostki budzą się po zadaniu im obrażeń. Jeśli cel został bezpośrednio zaatakowany, Koszmar przechodzi na atakującą jednostkę. Bane może swobodnie atakować i zadawać obrażenia jednostkom w stanie Koszmaru z dodatkową prędkością ataku.',
    10: 'INKANTACJA - Chwyta wrogą jednostkę, wyłączając ją z walki i zadając jej poważne obrażenia okresowe, jednocześnie co 0.5 s wykradając pewien procent maksymalnej many celu.',
  },
  4: {
    1: 'bloodrage',
    2: 'blood_bath',
    3: 'thirst',
    4: 'rupture',
    5: 'bloodrage',
    6: 'blood_mist',
    7: 'Wprowadza Bloodseekera w krwiożerczy szał, który powoduje u niego szybsze ataki i zadawanie większej ilości obrażeń od czarów kosztem procentu jego zdrowia na sekundę. Zapewnia połowę szybkości ataku sojuszniczym bohaterom.',
    8: 'Bloodseeker pokrywa obszar krwią sakralną. Po 2.9 s rytuał się zakończy, a przeciwnicy na jego obszarze otrzymają obrażenia i zostaną uciszeni.',
    9: 'Bloodseeker jest pobudzony ranami swoich wrogów, przywracając sobie trochę zdrowia, gdy zabija wrogą jednostkę. Przywraca połowę wartości podczas dobijania lub gdy sojusznik zabije pobliskiego wrogiego bohatera. Zyskuje również premię do szybkości ruchu, kiedy zdrowie wrogiego bohatera spadnie poniżej 80.0%. Premia będzie się zwiększać wraz ze spadkiem zdrowia bohatera. Jeśli zdrowie wrogiego bohatera spadnie poniżej 25.0%, Bloodseeker otrzyma widoczność i True Sight na tego bohatera. Te premie kumulują się za każdego bohatera. Zdejmuje limit szybkości ruchu dla Bloodseekera.',
    10: 'Bloodseeker rozpyla swoją krew ciągle w obszarze wokół niego, tracąc zdrowie, aby zadawać obrażenia i spowalniać swoich wrogów. Podczas aktywacji, leczenie z Umiejętności Pragnienia jest zwiększone. Nie można jej wyłączyć podczas okresu odnawiania. Dodatkowo, pasywnie przekształca nadmiar leczenia z twoich własnych umiejętności w barierę przed wszelkimi obrażeniami do 50% maksymalnego zdrowia Bloodseekera. Wartość bariery maleje o 0,5% na sekundę.',
  },
  5: {
    1: 'crystal_nova',
    2: 'frostbite',
    3: 'brilliance_aura',
    4: 'freezing_field',
    5: 'crystal_clone',
    6: 'freezing_field',
    7: 'Wybuch niszczycielskiego mrozu spowalnia szybkość ruchu oraz ataku wrogów na wyznaczonym obszarze.',
    8: 'Zamyka wrogą jednostkę w lodowej powłoce, uniemożliwiając jej poruszanie się oraz atakowanie i zadając obrażenia okresowe. Użyta na creepy poziomu 6. lub niższego trwa 10.0 s.',
    9: 'Daje dodatkową regenerację many wszystkim przyjaznym jednostkom na mapie. Sojusznicy znajdujący się w promieniu 1200,0 jednostek od Krystalicznej Damy otrzymują 3,0-krotnie większą regenerację many. Krystaliczna Dama sama otrzymuje 6,0-krotny bonus do regeneracji many.',
    10: 'Crystal Maiden odsuwa się do tyłu, tworząc krystalicznego klona samej siebie w miejscu rzutu czaru oraz rozłącza nadchodzące pociski. Jeśli klon odniesie wystarczającą ilość obrażeń lub minie wystarczająca ilość czasu, rozbija się na kawałki, nakładając efekt Frostbite na wrogów w obszarze o promieniu 400.0 jedn. wokół niego.',
  },
  6: {
    1: 'frost_arrows',
    2: 'wave_of_silence',
    3: 'multishot',
    4: 'marksmanship',
    5: 'aghs_shard',
    6: 'aghs_scepter',
    7: 'Dodaje efekt zamrożenia do strzał Drow Ranger, spowalniając szybkość ruchu wroga oraz zadając dodatkowe obrażenia. Trwa 1.5 s.',
    8: 'Wyzwala falę, która ucisza i odrzuca wrogie jednostki. Dystans odrzucenia zależy od tego, jak blisko znajduje się Drow Ranger. Drow Ranger zyskuje szybkość ruchu na taki sam czas trwania co uciszenie.',
    9: 'CHANNELED - Drow releases a flurry of arrows in continuous salvos, hitting enemies for extra damage and applying longer duration Frost Arrows. Lasts up to 1.8 seconds.',
    10: 'Drow Ranger creates a hill of ice beneath her. While standing on the hill, attackers gain bonus attack range and high ground advantage - they cannot miss and gain flying vision. Drow Ranger additionally gets bonus Multishot arrows per wave while on the hill. The front of the hill obscures vision and cannot be moved through except by Drow Ranger.',
  },
  7: {
    1: 'fissure',
    2: 'enchant_totem',
    3: 'aftershock',
    4: 'echo_slam',
    5: 'fissure',
    6: 'enchant_totem',
    7: 'Uderza w ziemię potężnym totemem, tworząc nieprzekraczalną kamienną grań oraz ogłuszając i zadając obrażenia wrogim jednostkom w linii.',
    8: 'Wzmacnia totem Earthshakera, zapewniając mu premię do obrażeń oraz premię 100.0 jednostek zasięgu ataku przy następnym ataku.',
    9: 'Powoduje, że ziemia trzęsie się pod stopami bohatera, zadając dodatkowe obrażenia i ogłuszając pobliskie wrogie jednostki za każdym razem, gdy Earthshaker używa swoich umiejętności.',
    10: 'Wyzwala falę uderzeniową, która zadaje obrażenia wrogim jednostkom. Każdy trafiony wróg powoduje pogłos, który zadaje obrażenia jednostkom w pobliżu. Prawdziwi bohaterowie powodują powstanie podwójnego echa.',
  },
};
